
```{r}
#| label: qpcr
#| tbl-cap: "Resultat fra qPCR"
#| warning: false
#| echo: false

library(gt)
library(dplyr)

df <- data.frame(Fortynningsrekke = c("1", "1/10", "1/100", "1/1000", "1/10000", "1/100000"),
                 Ct1 = c("26.09", "27.16", "28.42", "28.85", "30.00", "30.87"),
                 Ct2 = c("25.68", "27.76", "28.95", "29.36", "30.22", "30.68"),
                 Ct3 = c("25.86", "27.27", "27.64", "29.16", "34.92*", "31.19"),
                 Ct_gj_snitt = c("25.88", "27.40", "28.34", "29.13", "31.71", "30.91"),
                 Sample_quant = c("1", "0.5", "0.25", "0.12", "0.06", "0.03"),
                 Log_sample_quant = c("0.00", "-0.30", "-0.60", "-0.90", "-1.20", "-1.50"),
                 SD = c("0.21", "0.32", "0.65", "0.25", "2.78", "0.25"),
                 CV_prosent = c("1", "1", "2", "1", "9", "1"))

# Convert character columns to numeric
numeric_cols <- c("Ct1", "Ct2", "Ct3", "Ct_gj_snitt", "Sample_quant", "Log_sample_quant", "SD", "CV_prosent")
df[numeric_cols] <- lapply(df[numeric_cols], function(x) as.numeric(gsub("[*]", "", x)))

gt_table <- df %>%
  gt() %>%
  fmt_number(
    columns = vars(Ct1:CV_prosent),
    decimals = 2
  ) %>%
  fmt_missing(
    missing_text = "-"
  )

gt_table

```

```{r}
#| label: tbl-genuttrykk
#| tbl-cap: "Prosentvis andel genuttrykk for MHC I, IIa og IIx før og etter fem treningsøkter"
#| warning: false
#| message: false
#| echo: false

library(gt)

# Opprett dataframe med dataene
genuttrykk <- data.frame(
  Tidspunkt = c("W0", "W2"),
  MHC_I = c(18.16, 45.54),
  MHC_IIa = c(57.84, 85.77),
  MHC_IIx = c(24.01, 3.53)
)

genuttrykk %>%
  gt() %>%
  tab_spanner(
    label = "Genuttrykk",
    columns = c(MHC_I, MHC_IIa, MHC_IIx)
  ) %>%
  fmt_number(
    columns = c(MHC_I, MHC_IIa, MHC_IIx),
    decimals = 2
  )

#vis tabellen
genuttrykk
```

```{r}
#| label: tbl-mhc-cv
#| tbl-cap: "Gjennomsnittsverdier og CV for MHC I, IIa og IIx ved W0 og W2"
#| warning: false
#| message: false
#| echo: false

library(gt)

# Opprett data frame med gitt data
data <- data.frame(
  Time = c("W0", "W2"),
  MHC_I_mean = c(18.25, 20.61),
  MHC_I_STD = c(1.07, 4.85),
  MHC_I_CV = c(5.8, 23.52),
  MHC_IIa_mean = c(16.58, 17.61),
  MHC_IIa_STD = c(1.95, 0.69),
  MHC_IIa_CV = c(11.77, 3.93),
  MHC_IIx_mean = c(17.85, 22.21),
  MHC_IIx_STD = c(0.45, 0.72),
  MHC_IIx_CV = c(2.51, 3.26)
)

# Velg bare de kolonnene du ønsker å inkludere i tabellen
selected_columns <- c("Time", "MHC_I_mean", "MHC_IIa_mean", "MHC_IIx_mean", "MHC_I_CV", "MHC_IIa_CV", "MHC_IIx_CV")

# Opprett gt-tabell uten standardavvik
MHCCV <- data %>%
  dplyr::select(all_of(selected_columns)) %>%
  gt() %>%
  fmt_number(
    columns = vars(starts_with("MHC")),
    decimals = 2
  ) %>%
  tab_footnote("Mean = gjennomsnitt, CV = variasjonskoeffesient")

# Vis tabellen
MHCCV
```

